Задачи UiFormGroup, TheToaster, UiDropdown
js-tasks-ru/vue-20220419_oleg862 pull request #9
Opened 2022-05-12 08:22 UTC by VedemV

2022-05-12 08:23 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-05-13 15:51 UTC, ShGKme requested changes
В `TheToaster` предлагается сделать небольшие исправления по комментариям:
1. Убрать id из параметров компонента
2. Поменять параметры с классом и иконкой на тип.

Остальные задачи приняты.

2022-05-13 15:51 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
>        </button>
Кнопке не обязательно определять значение, чтобы работать через `$event.target.value`. Проще и лучше в метод обработки клика на кнопку передавать не `PointerEvent` от клика, а просто `option.value`. Главное в методе - не что он обрабатывает клик, а что он выбирает вариант.

2022-05-13 15:51 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +  },
Сейчас тост получает на вход не только сообщение, но и класс и иконку. Получается, что пользователь компонента должен сам знать, какая должна быть иконка у разных типов тостов и класс. При этом сами классы описаны в стилях именно этого компонента. Получается, что классы для разных типов иконки требуется достать из исходного кода (вёрстки) компонента при использовании этого компонента другим разработчикам. Если у нас есть явное определение, какой стиль и иконка у каких типов тостов, передавать в этот компонент лучше именно тип. А уже этот компонент будет сам решать, как этот тип тоста выводить.

2022-05-13 15:51 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +  },
Этому компоненту не нужен `id`, он фактически не используется в его работе.

2022-05-13 15:51 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +  },
Здесь `id` возвращается родителю. Родителю, который сам же этот `id` передал в тост. Получается, что родитель передаёт `id` чтобы в том же месте этот же самый id получить обратно.

2022-05-13 15:51 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    />
Здесь в метод `removeItem` можно явно передать `item.id`, не гоняя `id` через дочерний компонент.
`TheToasterItem` - просто удаляется. У него нет возможности удалиться как-то по-разному, с разными "данными" или разными `id`. `TheToaster` всегда знает, какой именно дочерний `TheToasterItem` удаляется, он сам вешает на него обработчик события.

2022-05-13 15:51 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToasterItem.vue
> +
Имена с префиксом `The` обычно используют для компонентов, которые выводятся на странице один раз. Артикул `The` в англ. показывает, что это "конкретный" компонент, что у него будет "один конкретный экземпляр".

2022-05-17 15:07 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-05-17 15:08 UTC, merged